# Generated by Django 3.2.3 on 2021-05-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activecode',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=200)),
            ],
            options={
                'db_table': 'ActiveCode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actives',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('regionid', models.IntegerField(blank=True, db_column='RegionId', null=True)),
                ('activecodeid', models.IntegerField(blank=True, db_column='ActiveCodeId', null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=0, max_digits=10, null=True)),
                ('creationdate', models.DateField(blank=True, db_column='CreationDate', null=True)),
            ],
            options={
                'db_table': 'Actives',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gasolineprices',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('gasolinetypeid', models.IntegerField(blank=True, db_column='GasolineTypeId', null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=0, max_digits=10, null=True)),
                ('creationdate', models.DateField(blank=True, db_column='CreationDate', null=True)),
            ],
            options={
                'db_table': 'GasolinePrices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gasolinetype',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'GasolineType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Methanepetrochemicals',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('price', models.BigIntegerField(blank=True, db_column='Price', null=True)),
                ('typeid', models.IntegerField(blank=True, db_column='TypeId', null=True)),
                ('producttypeid', models.IntegerField(blank=True, db_column='ProductTypeId', null=True)),
                ('creationdate', models.DateField(blank=True, db_column='CreationDate', null=True)),
            ],
            options={
                'db_table': 'MethanePetrochemicals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producttypes',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'ProductTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'Region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'Types',
                'managed': False,
            },
        ),
    ]
